# Generated by Django 3.1.1 on 2021-03-24 01:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('evento', models.CharField(max_length=250)),
                ('organizador', models.CharField(max_length=250)),
                ('fecha', models.DateField(blank=True, default=datetime.date.today)),
                ('telefono', models.CharField(max_length=13)),
                ('email', models.EmailField(max_length=254)),
                ('meta', models.IntegerField(default=100000)),
                ('costo', models.IntegerField(default=10000)),
                ('direccion', models.CharField(max_length=300)),
                ('ciudad', models.CharField(max_length=300)),
                ('descripcion', models.CharField(max_length=10000)),
                ('url', models.CharField(default='unidos-por-', max_length=250)),
                ('beneficiario', models.CharField(max_length=100)),
                ('latitud', models.DecimalField(decimal_places=20, default=0, max_digits=50)),
                ('longitud', models.DecimalField(decimal_places=20, default=0, max_digits=50)),
            ],
        ),
    ]
