# Generated by Django 3.1.1 on 2021-03-24 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='email',
        ),
        migrations.AddField(
            model_name='evento',
            name='medios',
            field=models.CharField(default='efectivo', max_length=500),
        ),
    ]
