# Generated by Django 3.1.1 on 2021-04-09 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_auto_20210323_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='categoria',
            field=models.CharField(default='todos', max_length=100),
        ),
    ]
