# Generated by Django 3.1.1 on 2021-04-16 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0003_evento_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='ciudad',
        ),
    ]
