# Generated by Django 3.1.1 on 2021-04-16 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0004_remove_evento_ciudad'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='ciudad',
            field=models.CharField(default='asuncion', max_length=300),
        ),
        migrations.AddField(
            model_name='evento',
            name='image',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
