# Generated by Django 3.1.1 on 2021-04-29 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0005_auto_20210415_2127'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emprendimiento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=250)),
                ('usuario', models.CharField(max_length=250)),
                ('telefono', models.CharField(max_length=13)),
                ('email', models.EmailField(max_length=254)),
                ('medios', models.CharField(default='efectivo', max_length=500)),
                ('direccion', models.CharField(max_length=300)),
                ('ciudad', models.CharField(default='asuncion', max_length=300)),
                ('image', models.FileField(blank=True, upload_to='')),
                ('descripcion', models.CharField(max_length=10000)),
                ('url', models.CharField(default='unidos-por-', max_length=250)),
                ('categoria', models.CharField(default='todos', max_length=100)),
                ('latitud', models.DecimalField(decimal_places=20, default=0, max_digits=50)),
                ('longitud', models.DecimalField(decimal_places=20, default=0, max_digits=50)),
            ],
        ),
        migrations.AddField(
            model_name='evento',
            name='enable_meta',
            field=models.BooleanField(default=True),
        ),
    ]
